---
- name: make directory for /etc/mongo/{{ env }}/scripts/
  file:
    dest: /etc/mongo/{{ env }}/scripts/
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
  tags: ldap_interval_change

- name: layout user template for the server
  template:
    src:  ldapintervalchange.js.j2
    dest: "/etc/mongo/{{ env }}/scripts/ldapintervalchange.js"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: '0644'
    force: yes
  tags: ldap_interval_change

- block:
  - name: set up users on config server
    shell: mongo {{ configsvr_rsa }}.opr.afsiep.net:{{ configsvr_rsa_port }}/admin /etc/mongo/{{ env }}/scripts/ldapintervalchange.js  
    register: config_result

  - name: show config shell result
    debug:
      var: config_result.stdout_lines
  when: (configsvr_rsa is defined) and (ansible_hostname == configsvr_rsa)
  ignore_errors: yes
  tags: ldap_interval_change

- block:
  - name: set up users on shard1a
    shell: mongo {{ shard1a }}.opr.afsiep.net:{{ shard1a_port }}/admin /etc/mongo/{{ env }}/scripts/ldapintervalchange.js 
    register: shard1_result

  - name: show shard1 shell result
    debug:
      var: shard1_result.stdout_lines
  when: (shard1a is defined) and (ansible_hostname == shard1a)
  ignore_errors: yes
  tags: ldap_interval_change

- block:
  - name: set up users on shard2a
    shell: mongo {{ shard2a }}.opr.afsiep.net:{{ shard2a_port }}/admin /etc/mongo/{{ env }}/scripts/ldapintervalchange.js  
    register: shard2_result

  - name: show shard2a shell result
    debug:
      var: shard2_result.stdout_lines
  when: (shard2a is defined) and (ansible_hostname == shard2a)
  ignore_errors: yes
  tags: ldap_interval_change

- block:
  - name: set up users on shard3a
    shell: mongo {{ shard3a }}.opr.afsiep.net:{{ shard3a_port }}/admin /etc/mongo/{{ env }}/scripts/ldapintervalchange.js  
    register: shard3_result
  - name: show shard3 shell result
    debug:
      var: shard3_result.stdout_lines
  when: (shard3a is defined) and (ansible_hostname == shard3a)
  ignore_errors: yes
  tags: ldap_interval_change
