---
# block for shard3a
- block:
  - name: make dbpath file directory /data/{{ env }}/shard3/rs_a
    file:
      path: /data/{{ env }}/shard3/rs_a
      state: directory
      mode: '2775'
      owner: "{{ owner }}"
      group: "{{ group }}"

  - name: layout template for /etc/mongo/{{ env }}/shard3_rs_a.cfg on the shard3 server
    template:
      src:  no_sec_shard3.conf.j2
      dest: "/etc/mongo/{{ env }}/shard3_rs_a.cfg"
      owner: "{{ owner }}"
      group: "{{ group }}"
      mode: '0644'
      force: yes

  - name: layout template for added mongod_shard3.service on the server
    template:
      src: mongod_shard3.service.j2
      dest: "/usr/lib/systemd/system/mongod_shard3.service"
      owner: "{{ owner }}"
      group: "{{ group }}"
      mode: '0640'
      force: yes

  - name: start mongod_shard3
    systemd:
      name: mongod_shard3
      state: restarted
      enabled: yes
      daemon_reload: yes
  when: (shard3a is defined) and (ansible_hostname == shard3a)
  ignore_errors: yes
  tags: shard3

# block for shard3b
- block:
  - name: make dbpath file directory /data/{{ env }}/shard3/rs_b
    file:
      path: /data/{{ env }}/shard3/rs_b
      state: directory
      mode: '2775'
      owner: "{{ owner }}"
      group: "{{ group }}"

  - name: layout template for /etc/mongo/{{ env }}/shard3_rs_b.cfg on the shard3 server
    template:
      src:  no_sec_shard3.conf.j2
      dest: "/etc/mongo/{{ env }}/shard3_rs_b.cfg"
      owner: "{{ owner }}"
      group: "{{ group }}"
      mode: '0644'
      force: yes

  - name: layout template for added mongod_shard3.service on the server
    template:
      src: mongod_shard3.service.j2
      dest: "/usr/lib/systemd/system/mongod_shard3.service"
      owner: "{{ owner }}"
      group: "{{ group }}"
      mode: '0640'
      force: yes

  - name: start mongod_shard3
    systemd:
      name: mongod_shard3
      state: restarted
      enabled: yes
      daemon_reload: yes
  when: (shard3b is defined) and (ansible_hostname == shard3b)
  ignore_errors: yes
  tags: shard3

# block for shard3c
- block:
  - name: make dbpath file directory /data/{{ env }}/shard3/rs_c
    file:
      path: /data/{{ env }}/shard3/rs_c
      state: directory
      mode: '2775'
      owner: "{{ owner }}"
      group: "{{ group }}"

  - name: layout template for /etc/mongo/{{ env }}/shard3_rs_c.cfg on the shard3 server
    template:
      src:  no_sec_shard3.conf.j2
      dest: "/etc/mongo/{{ env }}/shard3_rs_c.cfg"
      owner: "{{ owner }}"
      group: "{{ group }}"
      mode: '0644'
      force: yes

  - name: layout template for added mongod_shard3.service on the server
    template:
      src: mongod_shard3.service.j2
      dest: "/usr/lib/systemd/system/mongod_shard3.service"
      owner: "{{ owner }}"
      group: "{{ group }}"
      mode: '0640'
      force: yes

  - name: start mongod_shard3
    systemd:
      name: mongod_shard3
      state: restarted
      enabled: yes
      daemon_reload: yes
  when: (shard3c is defined) and (ansible_hostname == shard3c)
  ignore_errors: yes
  tags: shard3
