---
- block:
  - name: (add_shards.yml) make directory for /etc/mongo/{{ env }}/scripts/
    file:
      dest: /etc/mongo/{{ env }}/scripts/
      state: directory
      owner: "{{ owner }}"
      group: "{{ group }}"
    with_items: "{{ db_servers }}"
    loop_control:
      label: "{{ item.name }}"

  - name: (add_shards.yml) layout template on server
    template:
      src:  add_shards_to_cluster.js.j2
      dest: "/etc/mongo/{{ env }}/scripts/add_shards_to_cluster_{{ item.name }}.js"
      owner: "{{ owner }}"
      group: "{{ group }}"
      mode: '0644'
      force: yes
    with_items: "{{ db_servers }}"
    loop_control:
      label: "{{ item.name }}"

  - name: (add_shards.yml) add shards to cluster
    shell: mongo {{ ansible_fqdn }}:{{ item.port }}/admin /etc/mongo/{{ env }}/scripts/add_shards_to_cluster_{{ item.name }}.js -u amkanda -p Qwerty#12345px
    register: add_shards_result
    with_items: "{{ db_servers }}"
    loop_control:
      label: "{{ item.name }}"
    ignore_errors: yes

  - name: (add_shards.yml) show result
    debug:
      var: add_shards_result.stdout_lines
  ignore_errors: yes
  when: >
          ansible_hostname == {{ item.name }} and item.name == 'configsvr_rsa' or
          ansible_hostname == {{ item.name }} and item.name == 'shard1a' or
          ansible_hostname == {{ item.name }} and item.name == 'shard2a' or
          ansible_hostname == {{ item.name }} and item.name == 'shard3a' or
