---
# placing mongo.service file #
- name: (mongo_service.yml) layout mongo service template
  template:
    src:  "mongo.service.j2"
    dest: "/etc/systemd/system/mongo.service"
    owner: root
    group: root
    mode: '0640'
    force: yes
